import i18n from "@/i18n";

export interface LocalizedCategory {
  name: string;
  name_ru?: string | null;
  name_en?: string | null;
  slug?: string | null;
}

const FALLBACK_CATEGORY_NAMES: Record<string, { ru: string; en: string }> = {
  "geyim": { ru: "Одежда и мода", en: "Clothing & Fashion" },
  "ayaqqabi": { ru: "Обувь", en: "Shoes" },
  "canta-aksesuar": { ru: "Сумки и аксессуары", en: "Bags & Accessories" },
  "elektronika": { ru: "Электроника", en: "Electronics" },
  "ev-dekor": { ru: "Дом и декор", en: "Home & Decor" },
  "ev-aletleri": { ru: "Бытовая техника", en: "Home Appliances" },
  "gozellik": { ru: "Красота и уход", en: "Beauty & Personal Care" },
  "idman-hobi": { ru: "Спорт и хобби", en: "Sports & Hobby" },
  "usaq-korpe": { ru: "Детские товары", en: "Kids & Baby" },
  "pet-shop": { ru: "Зоотовары", en: "Pet Shop" },
  "supermarket": { ru: "Супермаркет", en: "Supermarket" },
  "saglamliq": { ru: "Здоровье и медицина", en: "Health & Medical" },
  "kitab-ofis": { ru: "Книги и офис", en: "Books & Office" },
  "avto-moto": { ru: "Авто и мото", en: "Auto & Moto" },
  "bagcilik": { ru: "Сад и огород", en: "Garden" },
  "geyim-qadin": { ru: "Женская одежда", en: "Women's clothing" },
  "geyim-kisi": { ru: "Мужская одежда", en: "Men's clothing" },
  "geyim-usaq": { ru: "Детская одежда", en: "Kids clothing" },
  "ayaqqabi-qadin": { ru: "Женская обувь", en: "Women's shoes" },
  "ayaqqabi-kisi": { ru: "Мужская обувь", en: "Men's shoes" },
  "ayaqqabi-usaq": { ru: "Детская обувь", en: "Kids shoes" },
  "aks-canta": { ru: "Сумки", en: "Bags" },
  "aks-cuzdan": { ru: "Кошельки и ремни", en: "Wallets & Belts" },
  "aks-saat": { ru: "Часы", en: "Watches" },
  "aks-eynek": { ru: "Очки", en: "Glasses" },
  "aks-zergerlik": { ru: "Украшения", en: "Jewelry" },
  "aks-papaq": { ru: "Шапки и шарфы", en: "Hats & Scarves" },
  "el-telefon": { ru: "Телефоны", en: "Phones" },
  "el-kompyuter": { ru: "Ноутбуки и ПК", en: "Laptops & PCs" },
  "el-tablet": { ru: "Планшеты", en: "Tablets" },
  "el-tv": { ru: "Телевизоры", en: "TVs" },
  "el-audio": { ru: "Наушники и аудио", en: "Headphones & Audio" },
  "el-foto": { ru: "Фото и видео", en: "Photo & Video" },
  "el-gaming": { ru: "Игры", en: "Gaming" },
  "el-smartwatch": { ru: "Умные часы", en: "Smartwatches" },
  "el-aksesuar": { ru: "Аксессуары", en: "Accessories" },
  "evd-mebel": { ru: "Мебель", en: "Furniture" },
  "evd-yataq": { ru: "Постельное белье", en: "Bedding" },
  "evd-xalca": { ru: "Ковры", en: "Carpets" },
  "evd-perde": { ru: "Шторы", en: "Curtains" },
  "evd-isiq": { ru: "Освещение", en: "Lighting" },
  "evd-metbex": { ru: "Кухонные принадлежности", en: "Kitchenware" },
  "evd-dekor": { ru: "Декор", en: "Decor" },
  "evd-saxlama": { ru: "Хранение", en: "Storage" },
  "mt-soyuducu": { ru: "Холодильники", en: "Refrigerators" },
  "mt-paltaryuyan": { ru: "Стиральные машины", en: "Washing machines" },
  "mt-qabyuyan": { ru: "Посудомоечные", en: "Dishwashers" },
  "mt-soba": { ru: "Плиты и духовки", en: "Stoves & Ovens" },
  "mt-kondisioner": { ru: "Кондиционеры", en: "Air conditioners" },
  "mt-kicik": { ru: "Мелкая бытовая техника", en: "Small appliances" },
  "mt-tozsoran": { ru: "Пылесосы", en: "Vacuum cleaners" },
  "gz-makiyaj": { ru: "Макияж", en: "Makeup" },
  "gz-deri": { ru: "Уход за кожей", en: "Skincare" },
  "gz-sac": { ru: "Уход за волосами", en: "Haircare" },
  "gz-etir": { ru: "Парфюмерия", en: "Perfume" },
  "gz-sexsi": { ru: "Личная гигиена", en: "Personal care" },
  "gz-manikur": { ru: "Маникюр и педикюр", en: "Manicure & Pedicure" },
  "ih-avadanliq": { ru: "Спортинвентарь", en: "Sports equipment" },
  "ih-geyim": { ru: "Спортивная одежда", en: "Sportswear" },
  "ih-kamp": { ru: "Туризм и кемпинг", en: "Outdoor & Camping" },
  "ih-velosiped": { ru: "Велосипеды и самокаты", en: "Bikes & Scooters" },
  "ih-hobi": { ru: "Хобби и коллекции", en: "Hobby & Collections" },
  "ih-musiqi": { ru: "Музыкальные инструменты", en: "Musical instruments" },
  "ih-baliqciliq": { ru: "Рыбалка", en: "Fishing" },
  "uk-qida": { ru: "Детское питание", en: "Baby food" },
  "uk-bez": { ru: "Подгузники и гигиена", en: "Diapers & Hygiene" },
  "uk-araba": { ru: "Коляски", en: "Strollers" },
  "uk-avto": { ru: "Автокресла", en: "Car seats" },
  "uk-oyuncaq": { ru: "Игрушки", en: "Toys" },
  "uk-otaq": { ru: "Детская комната", en: "Kids room" },
  "pet-it": { ru: "Товары для собак", en: "Dog products" },
  "pet-pisik": { ru: "Товары для кошек", en: "Cat products" },
  "pet-qus": { ru: "Товары для птиц", en: "Bird products" },
  "pet-balıq": { ru: "Аквариумы и рыбы", en: "Aquarium & fish" },
  "pet-kemirici": { ru: "Грызуны", en: "Rodents" },
  "sm-quru": { ru: "Бакалея", en: "Pantry" },
  "sm-icki": { ru: "Напитки", en: "Drinks" },
  "sm-sirni": { ru: "Сладости", en: "Sweets" },
  "sm-cay": { ru: "Чай и кофе", en: "Tea & Coffee" },
  "sm-sud": { ru: "Молочные", en: "Dairy" },
  "sm-temizlik": { ru: "Бытовая химия", en: "Cleaning" },
  "sg-vitamin": { ru: "Витамины и БАДы", en: "Vitamins & supplements" },
  "sg-cihaz": { ru: "Медтехника", en: "Medical devices" },
  "sg-apteka": { ru: "Аптечные товары", en: "Pharmacy" },
  "sg-optika": { ru: "Оптика", en: "Optics" },
  "ko-kitab": { ru: "Книги", en: "Books" },
  "ko-defter": { ru: "Канцтовары", en: "Stationery" },
  "ko-cap": { ru: "Печатная техника", en: "Printing equipment" },
  "ko-mebel": { ru: "Офисная мебель", en: "Office furniture" },
  "am-aksesuar": { ru: "Аксессуары", en: "Accessories" },
  "am-yag": { ru: "Масла и химия", en: "Oils & Chemicals" },
  "am-ehtiyat": { ru: "Запчасти", en: "Spare parts" },
  "am-elektronika": { ru: "Автоэлектроника", en: "Auto electronics" },
  "am-moto": { ru: "Мотоэкипировка", en: "Moto gear" },
  "bg-toxum": { ru: "Семена и растения", en: "Seeds & Plants" },
  "bg-aletler": { ru: "Садовые инструменты", en: "Garden tools" },
  "bg-gubre": { ru: "Удобрения и почва", en: "Fertilizer & Soil" },
  "bg-sulama": { ru: "Полив", en: "Watering" },
  "bg-mebel": { ru: "Садовая мебель", en: "Garden furniture" },
  "gq-paltar": { ru: "Платья", en: "Dresses" },
  "gq-bluz": { ru: "Блузки и рубашки", en: "Blouses & Shirts" },
  "gq-tisort": { ru: "Футболки", en: "T-shirts" },
  "gq-salvar": { ru: "Брюки и джинсы", en: "Pants & Jeans" },
  "gq-yubka": { ru: "Юбки", en: "Skirts" },
  "gq-sviter": { ru: "Свитера и кардиганы", en: "Sweaters & Cardigans" },
  "gq-pencek": { ru: "Пиджаки и блейзеры", en: "Jackets & Blazers" },
  "gq-palto": { ru: "Пальто и куртки", en: "Coats & Jackets" },
  "gq-don": { ru: "Платья и комбинезоны", en: "Dresses & Jumpsuits" },
  "gq-ic": { ru: "Нижнее белье", en: "Lingerie" },
  "gq-pijama": { ru: "Пижамы и сорочки", en: "Pajamas & Nightwear" },
  "gq-spor": { ru: "Спортивная одежда", en: "Sportswear" },
  "gq-uzgucu": { ru: "Купальники", en: "Swimwear" },
  "gk-tisort": { ru: "Футболки", en: "T-shirts" },
  "gk-koynek": { ru: "Рубашки", en: "Shirts" },
  "gk-salvar": { ru: "Брюки и джинсы", en: "Pants & Jeans" },
  "gk-sviter": { ru: "Свитера и кардиганы", en: "Sweaters" },
  "gk-kostyum": { ru: "Пиджаки и костюмы", en: "Suits & Blazers" },
  "gk-palto": { ru: "Пальто и куртки", en: "Coats & Jackets" },
  "gk-ic": { ru: "Нижнее белье", en: "Underwear" },
  "gk-pijama": { ru: "Пижамы", en: "Pajamas" },
  "gk-spor": { ru: "Спортивная одежда", en: "Sportswear" },
  "gu-korpe": { ru: "Малыши (0-2)", en: "Baby (0-2)" },
  "gu-qiz": { ru: "Для девочек", en: "Girls" },
  "gu-oglan": { ru: "Для мальчиков", en: "Boys" },
  "gu-mekteb": { ru: "Школьная форма", en: "School uniform" },
  "gu-pijama": { ru: "Пижамы", en: "Pajamas" },
  "gu-spor": { ru: "Спортивная одежда", en: "Sportswear" },
  "tel-apple": { ru: "Apple iPhone", en: "Apple iPhone" },
  "tel-samsung": { ru: "Samsung", en: "Samsung" },
  "tel-xiaomi": { ru: "Xiaomi", en: "Xiaomi" },
  "tel-huawei": { ru: "Huawei", en: "Huawei" },
  "tel-oppo": { ru: "Oppo", en: "Oppo" },
  "tel-oneplus": { ru: "OnePlus", en: "OnePlus" },
  "tel-vivo": { ru: "Vivo", en: "Vivo" },
  "tel-realme": { ru: "Realme", en: "Realme" },
  "tel-honor": { ru: "Honor", en: "Honor" },
  "tel-motorola": { ru: "Motorola", en: "Motorola" },
  "tel-nokia": { ru: "Nokia", en: "Nokia" },
  "tel-sony": { ru: "Sony", en: "Sony" },
  "tel-tuslu": { ru: "Кнопочные", en: "Feature phones" },
  "tel-qatlanan": { ru: "Складные", en: "Foldable" },
  "tel-refurb": { ru: "Восстановленные", en: "Refurbished" },
  "aq-daban": { ru: "На каблуке", en: "Heels" },
  "aq-duz": { ru: "Без каблука", en: "Flats" },
  "aq-sneaker": { ru: "Кроссовки", en: "Sneakers" },
  "aq-cekme": { ru: "Ботинки и сапоги", en: "Boots" },
  "aq-sandal": { ru: "Сандалии", en: "Sandals" },
  "aq-terlik": { ru: "Тапочки", en: "Slippers" },
  "aq-balerin": { ru: "Балетки", en: "Ballerinas" },
  "ak-klassik": { ru: "Классические", en: "Classic" },
  "ak-sneaker": { ru: "Кроссовки", en: "Sneakers" },
  "ak-cekme": { ru: "Ботинки", en: "Boots" },
  "ak-sandal": { ru: "Сандалии", en: "Sandals" },
  "ak-terlik": { ru: "Тапочки", en: "Slippers" },
  "ak-is": { ru: "Рабочая обувь", en: "Work shoes" },
  "au-korpe": { ru: "Для малышей", en: "Baby shoes" },
  "au-sneaker": { ru: "Кроссовки", en: "Sneakers" },
  "au-sandal": { ru: "Сандалии", en: "Sandals" },
  "au-cekme": { ru: "Ботинки", en: "Boots" },
  "au-mekteb": { ru: "Школьная обувь", en: "School shoes" },
};

export function catName(c: LocalizedCategory | null | undefined): string {
  if (!c) return "";
  const lang = i18n.resolvedLanguage || i18n.language || "az";
  if (lang.startsWith("ru") && c.name_ru) return c.name_ru;
  if (lang.startsWith("en") && c.name_en) return c.name_en;
  const fallback = c.slug ? FALLBACK_CATEGORY_NAMES[c.slug] : undefined;
  if (lang.startsWith("ru") && fallback?.ru) return fallback.ru;
  if (lang.startsWith("en") && fallback?.en) return fallback.en;
  return c.name;
}
