import i18n from "@/i18n";

export interface LocalizedCategory {
  name: string;
  name_ru?: string | null;
  name_en?: string | null;
  slug?: string | null;
}

const FALLBACK_CATEGORY_NAMES: Record<string, { ru: string; en: string }> = {
  elektronika: { ru: "Электроника", en: "Electronics" },
  "el-smartfon": { ru: "Смартфоны", en: "Smartphones" },
  "el-tel-aks": { ru: "Аксессуары для телефонов", en: "Phone accessories" },
  "el-noutbuk": { ru: "Ноутбуки", en: "Laptops" },
  "el-kompyuter": { ru: "Компьютеры", en: "Computers" },
  "el-monitor": { ru: "Мониторы", en: "Monitors" },
  "el-printer": { ru: "Принтеры", en: "Printers" },
  "el-smart-saat": { ru: "Смарт-часы", en: "Smart watches" },
  "el-planset": { ru: "Планшеты", en: "Tablets" },
  "el-konsol": { ru: "Игровые консоли", en: "Game consoles" },
  "el-tv": { ru: "Телевизоры", en: "TVs" },
  "el-audio": { ru: "Аудиосистемы", en: "Audio systems" },
  "el-kamera": { ru: "Камеры и фотоаппараты", en: "Cameras" },
  geyim: { ru: "Одежда", en: "Clothing" },
  "gey-qadin": { ru: "Женская одежда", en: "Women's clothing" },
  "gey-kisi": { ru: "Мужская одежда", en: "Men's clothing" },
  "gey-usaq": { ru: "Детская одежда", en: "Kids' clothing" },
  "gey-idman": { ru: "Спортивная одежда", en: "Sportswear" },
  "gey-alt": { ru: "Нижнее бельё", en: "Underwear" },
  "gey-cimerlik": { ru: "Пляжная одежда", en: "Beachwear" },
  "gey-is": { ru: "Рабочая одежда", en: "Workwear" },
  ayaqqabi: { ru: "Обувь", en: "Shoes" },
  "ay-qadin": { ru: "Женская обувь", en: "Women's shoes" },
  "ay-kisi": { ru: "Мужская обувь", en: "Men's shoes" },
  "ay-usaq": { ru: "Детская обувь", en: "Kids' shoes" },
  "ay-idman": { ru: "Спортивная обувь", en: "Sports shoes" },
  "ay-cekme": { ru: "Сапоги", en: "Boots" },
  "ay-sandal": { ru: "Сандалии", en: "Sandals" },
  aksesuarlar: { ru: "Аксессуары", en: "Accessories" },
  "aks-canta": { ru: "Сумки", en: "Bags" },
  "aks-pulqabi": { ru: "Кошельки", en: "Wallets" },
  "aks-kemer": { ru: "Ремни", en: "Belts" },
  "aks-saat": { ru: "Часы", en: "Watches" },
  "aks-eynek": { ru: "Очки", en: "Glasses" },
  "aks-zerger": { ru: "Ювелирные изделия", en: "Jewelry" },
  "gozellik-baxim": { ru: "Красота и уход", en: "Beauty & care" },
  "gz-kosmetika": { ru: "Косметика", en: "Cosmetics" },
  "gz-etir": { ru: "Парфюмерия", en: "Perfume" },
  "gz-sac": { ru: "Уход за волосами", en: "Hair care" },
  "gz-deri": { ru: "Уход за кожей", en: "Skin care" },
  "gz-makiyaj": { ru: "Макияж", en: "Makeup" },
  "gz-manikur": { ru: "Маникюр", en: "Manicure" },
  "ev-metbex": { ru: "Дом и кухня", en: "Home & kitchen" },
  "em-mebel": { ru: "Мебель", en: "Furniture" },
  "em-metbex": { ru: "Кухонные товары", en: "Kitchenware" },
  "em-qab": { ru: "Посуда", en: "Cookware" },
  "em-tekstil": { ru: "Текстиль", en: "Textiles" },
  "em-perde": { ru: "Шторы", en: "Curtains" },
  "em-isiq": { ru: "Освещение", en: "Lighting" },
  "em-dekor": { ru: "Декор", en: "Decor" },
  "ev-tekstili": { ru: "Домашний текстиль", en: "Home textile" },
  "et-yataq": { ru: "Постельные комплекты", en: "Bedding sets" },
  "et-yastiq": { ru: "Подушки", en: "Pillows" },
  "et-dosek": { ru: "Матрасы", en: "Mattresses" },
  "et-edyal": { ru: "Одеяла", en: "Blankets" },
  "et-desmal": { ru: "Полотенца", en: "Towels" },
  "usaq-korpe": { ru: "Дети и малыши", en: "Kids & baby" },
  "uk-oyuncaq": { ru: "Игрушки", en: "Toys" },
  "uk-araba": { ru: "Детские коляски", en: "Strollers" },
  "uk-qida": { ru: "Детское питание", en: "Baby food" },
  "uk-mebel": { ru: "Детская мебель", en: "Kids' furniture" },
  "uk-mekteb": { ru: "Школьные товары", en: "School supplies" },
  avtomobil: { ru: "Автомобиль", en: "Automotive" },
  "av-ehtiyat": { ru: "Запчасти", en: "Spare parts" },
  "av-yag": { ru: "Масла", en: "Oils" },
  "av-teker": { ru: "Шины", en: "Tires" },
  "av-aks": { ru: "Автоаксессуары", en: "Car accessories" },
  "av-alet": { ru: "Инструменты", en: "Tools" },
  "idman-istirahet": { ru: "Спорт и отдых", en: "Sports & leisure" },
  "id-fitness": { ru: "Фитнес-оборудование", en: "Fitness equipment" },
  "id-velosiped": { ru: "Велосипеды", en: "Bicycles" },
  "id-turizm": { ru: "Туризм", en: "Outdoor gear" },
  "id-baliq": { ru: "Рыбалка", en: "Fishing" },
  "id-ov": { ru: "Охотничьи аксессуары", en: "Hunting accessories" },
  "id-geyim": { ru: "Спортивная одежда", en: "Sportswear" },
  "heyvan-mehsullari": { ru: "Товары для животных", en: "Pet products" },
  "hv-yem": { ru: "Корма", en: "Pet food" },
  "hv-oyuncaq": { ru: "Игрушки", en: "Toys" },
  "hv-qefes": { ru: "Клетки", en: "Cages" },
  "hv-gigiyena": { ru: "Гигиена", en: "Hygiene" },
  "kitablar-defterxana": { ru: "Книги и канцелярия", en: "Books & stationery" },
  "kd-kitab": { ru: "Книги", en: "Books" },
  "kd-derslik": { ru: "Учебники", en: "Textbooks" },
  "kd-ofis": { ru: "Офисные принадлежности", en: "Office supplies" },
  "kd-defter": { ru: "Тетради", en: "Notebooks" },
  "kd-qelem": { ru: "Ручки", en: "Pens" },
  "erzaq-mehsullari": { ru: "Продукты", en: "Groceries" },
  "er-qehve": { ru: "Кофе", en: "Coffee" },
  "er-cay": { ru: "Чай", en: "Tea" },
  "er-sirni": { ru: "Сладости", en: "Sweets" },
  "er-konserv": { ru: "Консервы", en: "Canned food" },
  "er-quru": { ru: "Сухие продукты", en: "Dry groceries" },
  "er-icki": { ru: "Напитки", en: "Drinks" },
  "tikinti-temir": { ru: "Строительство и ремонт", en: "Construction & repair" },
  "tt-elektrik": { ru: "Электроматериалы", en: "Electrical materials" },
  "tt-santex": { ru: "Сантехника", en: "Plumbing" },
  "tt-boya": { ru: "Краски и лаки", en: "Paints" },
  "tt-alet": { ru: "Строительные инструменты", en: "Construction tools" },
  "tt-qapi": { ru: "Двери", en: "Doors" },
  "tt-doseme": { ru: "Напольные материалы", en: "Flooring" },
  "bag-heyat": { ru: "Сад и двор", en: "Garden & yard" },
  "bh-alet": { ru: "Садовые инструменты", en: "Garden tools" },
  "bh-toxum": { ru: "Семена", en: "Seeds" },
  "bh-bitki": { ru: "Растения", en: "Plants" },
  "bh-suvarma": { ru: "Системы полива", en: "Watering systems" },
  "aptek-saglamliq": { ru: "Аптека и здоровье", en: "Pharmacy & health" },
  "ap-vitamin": { ru: "Витамины", en: "Vitamins" },
  "ap-cihaz": { ru: "Медицинские устройства", en: "Medical devices" },
  "ap-gigiyena": { ru: "Гигиенические товары", en: "Hygiene products" },
  "ap-bandaj": { ru: "Бандажи", en: "Bandages" },
  "hediyyeler-suvenirler": { ru: "Подарки и сувениры", en: "Gifts & souvenirs" },
  "hd-deste": { ru: "Подарочные наборы", en: "Gift sets" },
  "hd-dekor": { ru: "Декоративные товары", en: "Decorative items" },
  "hd-bayram": { ru: "Праздничные товары", en: "Holiday products" },
};

export function catName(c: LocalizedCategory | null | undefined): string {
  if (!c) return "";
  const lang = i18n.resolvedLanguage || i18n.language || "az";
  if (lang.startsWith("ru") && c.name_ru) return c.name_ru;
  if (lang.startsWith("en") && c.name_en) return c.name_en;
  const fallback = c.slug ? FALLBACK_CATEGORY_NAMES[c.slug] : undefined;
  if (lang.startsWith("ru") && fallback?.ru) return fallback.ru;
  if (lang.startsWith("en") && fallback?.en) return fallback.en;
  return c.name;
}
