import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { ProductCard } from "@/components/ProductCard";
import { products } from "@/data/staticStore";
import { Flame, Heart, Tag, Sparkles, TrendingUp } from "lucide-react";
export const Route = createFileRoute("/discover")({ head: () => ({ meta: [{ title: "Discover — EG Shop" }] }), component: Discover });
type Tab = "trending" | "discounted" | "favorites" | "newest" | "topRated";
function Discover() { const { t } = useTranslation(); const [tab, setTab] = useState<Tab>("trending"); const TABS = [{ id: "trending" as const, label: t("discover.tabTrending"), icon: Flame, color: "from-orange-500 to-red-500" }, { id: "discounted" as const, label: t("discover.tabDiscounted"), icon: Tag, color: "from-rose-500 to-pink-500" }, { id: "favorites" as const, label: t("discover.tabFavorites"), icon: Heart, color: "from-pink-500 to-fuchsia-500" }, { id: "topRated" as const, label: t("discover.tabTopRated"), icon: TrendingUp, color: "from-amber-500 to-yellow-500" }, { id: "newest" as const, label: t("discover.tabNewest"), icon: Sparkles, color: "from-violet-500 to-indigo-500" }]; const active = TABS.find((x) => x.id === tab)!; let list = [...products]; if (tab === "discounted") list = list.filter((p) => p.old_price); else if (tab === "topRated") list.sort((a,b)=>b.rating-a.rating); else if (tab === "trending" || tab === "favorites") list.sort((a,b)=>b.reviews_count-a.reviews_count); return <div className="container mx-auto px-4 py-6 space-y-6"><div className={`rounded-3xl p-6 md:p-10 text-white bg-gradient-to-br ${active.color} shadow-elegant relative overflow-hidden`}><div className="relative z-10"><div className="inline-flex items-center gap-2 bg-white/20 backdrop-blur px-3 py-1 rounded-full text-xs font-bold mb-3"><active.icon className="h-3.5 w-3.5" /> {t("discover.headerBadge")}</div><h1 className="text-3xl md:text-5xl font-black leading-tight">{active.label}</h1><p className="opacity-90 mt-2 text-sm md:text-base">{t("discover.headerDesc")}</p></div></div><div className="flex gap-2 overflow-x-auto -mx-4 px-4 pb-2 scrollbar-none">{TABS.map((tt) => <button key={tt.id} onClick={() => setTab(tt.id)} className={`shrink-0 inline-flex items-center gap-2 px-4 py-2.5 rounded-full text-sm font-bold transition border-2 ${tab === tt.id ? `bg-gradient-to-r ${tt.color} text-white border-transparent shadow-card` : "bg-card border-border hover:border-primary text-foreground"}`}><tt.icon className="h-4 w-4" />{tt.label}</button>)}</div>{list.length === 0 ? <div className="text-center py-20 bg-secondary/40 rounded-2xl"><p className="text-muted-foreground">{t("discover.empty")}</p><Link to="/catalog" search={{ q: undefined, cat: undefined } as never} className="text-primary font-semibold hover:underline">{t("discover.goToCatalog")}</Link></div> : <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-3 md:gap-4">{list.map((p) => <ProductCard key={p.id} p={p} />)}</div>}</div>; }
