/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ShopsRouteImport } from './routes/shops'
import { Route as PromotionsRouteImport } from './routes/promotions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PickupPointsRouteImport } from './routes/pickup-points'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIdRouteImport } from './routes/shop.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsRoute = ShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionsRoute = PromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupPointsRoute = PickupPointsRouteImport.update({
  id: '/pickup-points',
  path: '/pickup-points',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIdRoute = ShopIdRouteImport.update({
  id: '/shop/$id',
  path: '/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/pickup-points': typeof PickupPointsRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/shops': typeof ShopsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/pickup-points': typeof PickupPointsRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/shops': typeof ShopsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/discover': typeof DiscoverRoute
  '/pickup-points': typeof PickupPointsRoute
  '/privacy': typeof PrivacyRoute
  '/promotions': typeof PromotionsRoute
  '/shops': typeof ShopsRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$id': typeof ShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/contact'
    | '/discover'
    | '/pickup-points'
    | '/privacy'
    | '/promotions'
    | '/shops'
    | '/support'
    | '/terms'
    | '/product/$id'
    | '/shop/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/contact'
    | '/discover'
    | '/pickup-points'
    | '/privacy'
    | '/promotions'
    | '/shops'
    | '/support'
    | '/terms'
    | '/product/$id'
    | '/shop/$id'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/contact'
    | '/discover'
    | '/pickup-points'
    | '/privacy'
    | '/promotions'
    | '/shops'
    | '/support'
    | '/terms'
    | '/product/$id'
    | '/shop/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  DiscoverRoute: typeof DiscoverRoute
  PickupPointsRoute: typeof PickupPointsRoute
  PrivacyRoute: typeof PrivacyRoute
  PromotionsRoute: typeof PromotionsRoute
  ShopsRoute: typeof ShopsRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopIdRoute: typeof ShopIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops': {
      id: '/shops'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotions': {
      id: '/promotions'
      path: '/promotions'
      fullPath: '/promotions'
      preLoaderRoute: typeof PromotionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup-points': {
      id: '/pickup-points'
      path: '/pickup-points'
      fullPath: '/pickup-points'
      preLoaderRoute: typeof PickupPointsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$id': {
      id: '/shop/$id'
      path: '/shop/$id'
      fullPath: '/shop/$id'
      preLoaderRoute: typeof ShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  DiscoverRoute: DiscoverRoute,
  PickupPointsRoute: PickupPointsRoute,
  PrivacyRoute: PrivacyRoute,
  PromotionsRoute: PromotionsRoute,
  ShopsRoute: ShopsRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ProductIdRoute: ProductIdRoute,
  ShopIdRoute: ShopIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
