ALTER TABLE public.categories
  ADD COLUMN IF NOT EXISTS name_ru text,
  ADD COLUMN IF NOT EXISTS name_en text;

-- Auto-fill known translations by slug
UPDATE public.categories SET
  name_ru = COALESCE(name_ru, CASE slug
    WHEN 'electronics' THEN 'Электроника'
    WHEN 'phones' THEN 'Телефоны'
    WHEN 'smartphones' THEN 'Смартфоны'
    WHEN 'laptops' THEN 'Ноутбуки'
    WHEN 'computers' THEN 'Компьютеры'
    WHEN 'tablets' THEN 'Планшеты'
    WHEN 'tv' THEN 'Телевизоры'
    WHEN 'audio' THEN 'Аудио'
    WHEN 'headphones' THEN 'Наушники'
    WHEN 'cameras' THEN 'Камеры'
    WHEN 'gaming' THEN 'Игры'
    WHEN 'accessories' THEN 'Аксессуары'
    WHEN 'fashion' THEN 'Мода'
    WHEN 'clothing' THEN 'Одежда'
    WHEN 'men' THEN 'Мужское'
    WHEN 'women' THEN 'Женское'
    WHEN 'kids' THEN 'Детское'
    WHEN 'shoes' THEN 'Обувь'
    WHEN 'bags' THEN 'Сумки'
    WHEN 'watches' THEN 'Часы'
    WHEN 'jewelry' THEN 'Украшения'
    WHEN 'beauty' THEN 'Красота'
    WHEN 'cosmetics' THEN 'Косметика'
    WHEN 'perfume' THEN 'Парфюмерия'
    WHEN 'health' THEN 'Здоровье'
    WHEN 'home' THEN 'Дом'
    WHEN 'furniture' THEN 'Мебель'
    WHEN 'kitchen' THEN 'Кухня'
    WHEN 'appliances' THEN 'Бытовая техника'
    WHEN 'garden' THEN 'Сад'
    WHEN 'tools' THEN 'Инструменты'
    WHEN 'sports' THEN 'Спорт'
    WHEN 'fitness' THEN 'Фитнес'
    WHEN 'outdoor' THEN 'Туризм'
    WHEN 'toys' THEN 'Игрушки'
    WHEN 'baby' THEN 'Для малышей'
    WHEN 'books' THEN 'Книги'
    WHEN 'stationery' THEN 'Канцтовары'
    WHEN 'auto' THEN 'Авто'
    WHEN 'automotive' THEN 'Автотовары'
    WHEN 'food' THEN 'Продукты'
    WHEN 'grocery' THEN 'Бакалея'
    WHEN 'drinks' THEN 'Напитки'
    WHEN 'pets' THEN 'Питомцы'
    WHEN 'pet' THEN 'Питомцы'
    WHEN 'office' THEN 'Офис'
    WHEN 'art' THEN 'Искусство'
    WHEN 'music' THEN 'Музыка'
    WHEN 'gifts' THEN 'Подарки'
    ELSE name
  END),
  name_en = COALESCE(name_en, CASE slug
    WHEN 'electronics' THEN 'Electronics'
    WHEN 'phones' THEN 'Phones'
    WHEN 'smartphones' THEN 'Smartphones'
    WHEN 'laptops' THEN 'Laptops'
    WHEN 'computers' THEN 'Computers'
    WHEN 'tablets' THEN 'Tablets'
    WHEN 'tv' THEN 'TVs'
    WHEN 'audio' THEN 'Audio'
    WHEN 'headphones' THEN 'Headphones'
    WHEN 'cameras' THEN 'Cameras'
    WHEN 'gaming' THEN 'Gaming'
    WHEN 'accessories' THEN 'Accessories'
    WHEN 'fashion' THEN 'Fashion'
    WHEN 'clothing' THEN 'Clothing'
    WHEN 'men' THEN 'Men'
    WHEN 'women' THEN 'Women'
    WHEN 'kids' THEN 'Kids'
    WHEN 'shoes' THEN 'Shoes'
    WHEN 'bags' THEN 'Bags'
    WHEN 'watches' THEN 'Watches'
    WHEN 'jewelry' THEN 'Jewelry'
    WHEN 'beauty' THEN 'Beauty'
    WHEN 'cosmetics' THEN 'Cosmetics'
    WHEN 'perfume' THEN 'Perfume'
    WHEN 'health' THEN 'Health'
    WHEN 'home' THEN 'Home'
    WHEN 'furniture' THEN 'Furniture'
    WHEN 'kitchen' THEN 'Kitchen'
    WHEN 'appliances' THEN 'Appliances'
    WHEN 'garden' THEN 'Garden'
    WHEN 'tools' THEN 'Tools'
    WHEN 'sports' THEN 'Sports'
    WHEN 'fitness' THEN 'Fitness'
    WHEN 'outdoor' THEN 'Outdoor'
    WHEN 'toys' THEN 'Toys'
    WHEN 'baby' THEN 'Baby'
    WHEN 'books' THEN 'Books'
    WHEN 'stationery' THEN 'Stationery'
    WHEN 'auto' THEN 'Auto'
    WHEN 'automotive' THEN 'Automotive'
    WHEN 'food' THEN 'Food'
    WHEN 'grocery' THEN 'Grocery'
    WHEN 'drinks' THEN 'Drinks'
    WHEN 'pets' THEN 'Pets'
    WHEN 'pet' THEN 'Pets'
    WHEN 'office' THEN 'Office'
    WHEN 'art' THEN 'Art'
    WHEN 'music' THEN 'Music'
    WHEN 'gifts' THEN 'Gifts'
    ELSE name
  END);